enum NotificationKind { trustedContact, escalation, emergency }

extension NotificationKindX on NotificationKind {
  String get tagLabel {
    switch (this) {
      case NotificationKind.trustedContact:
        return 'Trusted contact';
      case NotificationKind.escalation:
        return 'Escalation';
      case NotificationKind.emergency:
        return 'Emergency';
    }
  }
}

/// A real in-app notification generated by an actual event (SOS sent,
/// escalation triggered, a responder marking they're on it) — never
/// placeholder content shown just to fill the screen.
class AppNotification {
  final String id;
  final String title;
  final String body;
  final NotificationKind kind;
  final DateTime createdAt;

  const AppNotification({
    required this.id,
    required this.title,
    required this.body,
    required this.kind,
    required this.createdAt,
  });

  String get relativeTime {
    final diff = DateTime.now().difference(createdAt);
    if (diff.inSeconds < 60) return 'Just now';
    if (diff.inMinutes < 60) return '${diff.inMinutes} min ago';
    if (diff.inHours < 24) return '${diff.inHours} h ago';
    return '${diff.inDays} d ago';
  }
}
