const express = require("express");
const { sendRequest, receivedRequests, acceptRequest, rejectRequest } = require("../controllers/trustRequestController");
const protect = require("../middleware/authMiddleware");
const router = express.Router();
router.use(protect);
router.post("/", sendRequest);
router.get("/received", receivedRequests);
router.post("/:id/accept", acceptRequest);
router.post("/:id/reject", rejectRequest);
module.exports = router;
