// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_vN3NourfrOEecqp_skThc9sZuOcjyVw',
    appId: '1:877537026627:web:aa5a623b1f48f8ac736af6',
    messagingSenderId: '877537026627',
    projectId: 'safetyu-58f4a',
    authDomain: 'safetyu-58f4a.firebaseapp.com',
    storageBucket: 'safetyu-58f4a.firebasestorage.app',
    measurementId: 'G-Z9179VEDB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aHL5b88w0Gxm1J-GADUSDmtxjTgyCBI',
    appId: '1:877537026627:android:030ee050e82fc9ea736af6',
    messagingSenderId: '877537026627',
    projectId: 'safetyu-58f4a',
    storageBucket: 'safetyu-58f4a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0enUpDfiF9zeaRe6gqgU3dSV1roZxug',
    appId: '1:877537026627:ios:98ccdff1e50b332a736af6',
    messagingSenderId: '877537026627',
    projectId: 'safetyu-58f4a',
    storageBucket: 'safetyu-58f4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj0enUpDfiF9zeaRe6gqgU3dSV1roZxug',
    appId: '1:877537026627:ios:98ccdff1e50b332a736af6',
    messagingSenderId: '877537026627',
    projectId: 'safetyu-58f4a',
    storageBucket: 'safetyu-58f4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_vN3NourfrOEecqp_skThc9sZuOcjyVw',
    appId: '1:877537026627:web:a3b2f9a4fe441d65736af6',
    messagingSenderId: '877537026627',
    projectId: 'safetyu-58f4a',
    authDomain: 'safetyu-58f4a.firebaseapp.com',
    storageBucket: 'safetyu-58f4a.firebasestorage.app',
    measurementId: 'G-D4BXHB5YCQ',
  );
}
